language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_BRANCH=master
    - php: 5.4
      env: TYPO3_BRANCH=master

env:
  global:
    secure: "1D18A3jmTjffGsWlszvQS2vfI5oLCcUeixI7J9P3JHD9/T9/Z+D36RSP+j6/bG8xSBQLWSaWbTBXNhyH0jgcZ61DjQvwv46/SgsGjzJ4rmJhJ7mCv5AO6UiamHr9my+hEnh3Hu1ngZ6h36dPRMS9iIiNk6RzARMiBJCh5MLfI+k="
  matrix:
    - TYPO3_BRANCH=master
    - TYPO3_BRANCH=TYPO3_6-2

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - helmut@typo3.org

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p typo3conf/ext
  - cp typo3_console/Scripts/typo3cms .
  - mv typo3_console typo3conf/ext/

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/typo3_console/Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/typo3_console/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
# Basic functional tests - all commands should exit with 0
  - ./typo3cms help && [ ! -f "typo3conf/PackageStates.php" ]
  - ./typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="localhost" --database-port="3306" --database-name="travis_test" --admin-user-name="admin" --admin-password="password" --site-name="Travis Install"
  - ./typo3cms help
  - ./typo3cms cache:flush
  - ./typo3cms cache:listgroups
  - ./typo3cms cache:warmup
  - ./typo3cms backend:lock
  - ./typo3cms backend:unlock
  - ./typo3cms cleanup:updatereferenceindex